""" version which can be consumed from within the module """
VERSION_STR = "0.0.15"
DESCRIPTION = "pypluggy is a lightweight plugin framework for python"
APP_NAME = "pypluggy"
LOGGER_NAME = "pypluggy"
